_target_: rl4co.models.AMPPO

policy_kwargs:
  embed_dim: 128
  num_encoder_layers: 3
  num_heads: 8
  encoder:
    _target_: rl4co.models.nn.graph.pc_encoder.PCEdgeAwareEncoder
    embed_dim: ${model.policy_kwargs.embed_dim}
    num_layers: ${model.policy_kwargs.num_encoder_layers}
    env_name: pc
    edge_input_dim: 8
    use_compat_mask: false
    use_message_mask: false
    include_connection_feature: true
    exclude_sep_from_encoder: true

critic_kwargs:
  embed_dim: ${model.policy_kwargs.embed_dim}

mini_batch_size: 64
ppo_epochs: 2
vf_lambda: 0.5
entropy_lambda: 0.001

metrics:
  train: ["loss", "reward", "surrogate_loss", "value_loss", "value_loss_term", "entropy", "entropy_loss"]
  val: ["reward"]
  test: ${model.metrics.val}
  log_on_step: True
