_target_: rl4co.models.POMO

# PC does not use geometric dihedral augmentation by default.
num_augment: 1
num_starts: 4

policy_kwargs:
  embed_dim: 128
  num_encoder_layers: 3
  num_heads: 8
  normalization: "batch"
  use_graph_context: True

metrics:
  train: ["loss", "reward", "max_reward"]
  val: ["reward", "max_reward"]
  test: ${model.metrics.val}
  log_on_step: True
